name: country_search
description: A beautiful and customizable country picker widget for Flutter with multi-language support, phone codes, and smart search functionality.
version: 2.0.2
homepage: https://github.com/stanislavworldin/flutter_country_picker
repository: https://github.com/stanislavworldin/flutter_country_picker
issue_tracker: https://github.com/stanislavworldin/flutter_country_picker/issues
documentation: https://github.com/stanislavworldin/flutter_country_picker#readme
topics:
  - flags
  - country
  - picker
  - search
  - phone-codes

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No assets needed for this package screenshots:

screenshots:
  - description: "Country Picker with search functionality"
    path: screenshots/1.png
