name: fuzzy_search
description: Fast and lightweight search engine for Dart/Flutter with fuzzy search capabilities — lightweight and flexible.
version: 1.0.0
homepage: https://github.com/stanislavworldin/search
repository: https://github.com/stanislavworldin/search
issue_tracker: https://github.com/stanislavworldin/search/issues
documentation: https://github.com/stanislavworldin/search#readme
topics:
  - search
  - fuzzy-search
  - engine
  - items
  - filtering

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # No dependencies needed - pure Dart implementation

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

# No assets needed for this package
