name: country_search
description: A beautiful and customizable country picker widget with search functionality, multi-language support, and phone codes.
version: 2.3.2
homepage: https://github.com/stanislavworldin/country_search
repository: https://github.com/stanislavworldin/country_search
issue_tracker: https://github.com/stanislavworldin/country_search/issues
documentation: https://github.com/stanislavworldin/country_search#readme
topics:
  - flags
  - country
  - picker
  - search
  - phone-codes

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No assets needed for this package screenshots:

screenshots:
  - description: "Country Picker with search functionality"
    path: screenshots/1.png
